FROM node:16-alpine

RUN mkdir -p /var/www/dockerize-nuxt/nuxt-app
WORKDIR /var/www/dockerize-nuxt/nuxt-app

RUN npm install -g pnpm

COPY ./leaderboard-site .
RUN pnpm install

ENV BACKEND_BASE_URL=http://backend:5142

RUN pnpm build
CMD [ "pnpm", "start" ]
